Add PG username and password env variables
questdb/questdb-kubernetes pull request #116
Opened 2023-01-27 18:54 UTC by mariusgheorghies

2023-01-30 17:12 UTC, sklarsa requested changes

2023-01-30 17:12 UTC, sklarsa commented on charts/questdb/values.yaml
> +existingSecrets: {}
It would be nice to be able to map existing secret keys to env vars in the pod.  Otherwise, we need to document the expected keys in the existing secret (`password`, `readonly-password`, ... )

2023-01-30 17:12 UTC, sklarsa commented on charts/questdb/templates/secret.yaml
> +{{- if .Values.generateSecrets.psqlSecret.enabled }}
If a user enables both `existingSecrets` and `generateSecrets` (because they didn't read the docs :-)), this leads to a new secret being created with the existing secret _name_ and the generated _values_, which is confusing at best and would cause an error if the secret already exists.

I think you should add a `and not .values.existingSecrets.pgSecretName` to this condition guard against this.  It would also create a priority of existing secrets over generated secrets, which makes sense to me

2023-01-31 09:14 UTC, mariusgheorghies commented on charts/questdb/templates/secret.yaml
> +{{- if .Values.generateSecrets.psqlSecret.enabled }}
Ya, saw that but my thinking was not to delete the secret until the user will put `enable: false`, because it will make a revert a bit more painful if we delete the secret. But i guess this can be expected when one is filling up the `existingSecrets` map

2023-01-31 09:18 UTC, mariusgheorghies commented
There is also this `pg.readonly.user.enabled`  config line that i have to set it to true but i don't know if i should set it in the env variables or let the user set it in the `serverConfig`.

2023-09-21 18:19 UTC, closed without merging