Make it possible to store server.conf and log.conf as Secret
questdb/questdb-kubernetes pull request #169
Opened 2024-09-16 08:14 UTC by wiesom

Because server.conf can contain secrets such as passwords it would be convenient to be able to store the complete server.conf as a Secret instead of a ConfigMap.

With this change it will be possible to the change config store type be setting `questdb.configStorageType=Secret`

2024-09-16 08:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/questdb/questdb-kubernetes?pullRequest=169) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/questdb/questdb-kubernetes?pullRequest=169) before we can accept your contribution.<br/><hr/>**Mats Löfgren** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/questdb/questdb-kubernetes?pullRequest=169) it.</sub>

2024-09-16 20:39 UTC, sklarsa requested changes

2024-09-16 20:39 UTC, sklarsa commented on charts/questdb/templates/config-map.yaml
> +kind: Secret
I would prefer if we keep the secret and configmap yaml in separate template files, which seems to be the way that people do things in helm charts these days.  While this does lead to a bit of config duplication, IMO it makes it significantly easier to understand what's going on in each template.

2024-09-17 06:51 UTC, wiesom commented on charts/questdb/templates/config-map.yaml
> +kind: Secret
Thanks for you input.
The downside I can see with having two different files in this case is that they easily can become out of sync.
By having it in the same file it become obvious that they are mutually exclusive, you can't use both the secret and the config map.

Maybe we could both the secret and the configmap in the same file but not mixed togeheter like it is right now?
Something like this:
```
{{- if eq .Values.questdb.configStorageType "Secret"}}
apiVersion: :v1
kind: Secret
...

{{- else }}
apiVersion: :v1
kind: ConfigMap

{{- end }}
```

FYI. when I created the PR I looked how Grafana Loki solved the same problem
https://github.com/grafana/loki/blob/main/production/helm/loki/templates/config.yaml

2024-09-17 13:36 UTC, sklarsa requested changes

2024-09-17 13:36 UTC, sklarsa commented on charts/questdb/templates/config-map.yaml
> +kind: Secret
Thanks, you make some good points, and I especially like that grafana example. Let's go in that direction by leaving the file as-is and just renaming it to `config.yaml`. This way there's no confusion about modifying a secret in a template called `config-map.yaml`.

2024-09-17 14:44 UTC, sklarsa approved these changes

2024-09-17 14:45 UTC, merged

2024-09-17 14:50 UTC, sklarsa commented
All set, just cut 0.40.7! Thanks for the PRs, and let us know if you have any issues